### ISSUE TITLE
Реализовать получение id целевой ветки по номеру pr

### ISSUE THREAD

**Issue by akaguny** [akaguny/advanced-build-conditions#1]
Для этого необходимо доработать модуль teamcity, добавив функции получения id pr, проекта, а также репозитория по ветке которого выполняется сборка.
Также необходимо разработать модуль bitbucket, реализующий функционал получения id пулл-реквеста по id ветки и id целевой ветки по id пулл-реквеста

**Comment by akaguny** [comment]
добавить выставление build.number(teamcity) в branchID(bitbucket)

**Comment by akaguny** [comment]
Решено заморозить разработку фичи как низкоприоритетной, потому как:
* мерж не в мастер ветку происходит не так часто
* усли показатели хуже чем в мастер ветке, то надо сначала решить эту проблему

**Comment by sharikovvladislav** [comment]
Для API TC: https://github.com/peter-murray/node-teamcity-api

**Comment by akaguny** [comment]
@sharikovvladislav по teamcity уже сделано общение с restApi, я смотрел что есть в модулях перед началом работы, ничего н епонравилось

**Comment by sharikovvladislav** [comment]
А, тру. Недоосознал. Это конечно относится к работе с ТС.

**Comment by sharikovvladislav** [comment]
Всё хрень? https://www.npmjs.com/browse/keyword/stash

Просто я делал пакет для работы с ТС и приятного было мало. Много дебага и мутные вызовы. Если есть обёртка норм я бы воспользовался ей.

**Comment by akaguny** [comment]
@sharikovvladislav всё конечно не пробовал. Я написал с учётом необходимости поддержки
